# Generated by Django 4.2.1 on 2024-04-29 19:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorcompany',
            name='company_utilities',
            field=colorfield.fields.ColorField(blank=True, default='#6246ea)', image_field=None, max_length=25, null=True, samples=None, verbose_name='Color Contenedor Utilerias'),
        ),
    ]
