# Generated by Django 4.2.1 on 2024-03-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ubicación'),
        ),
    ]
